name: annonars-clinvar-genes-import
description: Run "annonars clinvar-genes import"

inputs:
  publish-artifacts:
    default: "false"
    description: "Whether to publish artifacts to the named release"
  release-name:
    description: "The name of the release to publish artifacts to"
  token:
    description: 'A Github PAT'
    required: true

runs:
  using: "composite"
  steps:
    - name: setup git config
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "<>"
      # cf. https://github.com/mamba-org/provision-with-micromamba#important
      shell: bash -l {0}

    - name: Get ClinVar version
      id: get-clinvar
      run: echo "clinvar-release=$(cat clinvar-release.txt)" >> $GITHUB_OUTPUT
      # cf. https://github.com/mamba-org/provision-with-micromamba#important
      shell: bash -l {0}

    - name: Check cache annonars-clinvar-genes-import output
      id: check-cache-annonars-clinvar-genes-import-output
      uses: actions/cache@v3
      with:
        path: ${{ env.OUTPUT_DIR }}/${{ matrix.genome_release }}/seqvar/annonars-import
        key: annonars-clinvar-genes-import-${{ env.CACHE_SEED }}-${{ steps.get-clinvar.outputs.clinvar-release }}-${{ env.MAX_RCVS }}-${{ matrix.genome_release }}
        lookup-only: true

    - name: Install Conda environment
      if: steps.check-cache-annonars-clinvar-genes-import-output.outputs.cache-hit != 'true'
      uses: mamba-org/setup-micromamba@v1
      with:
        cache-environment: true
        environment-name: annonars-data-clinvar
        condarc: |
          channels:
            - conda-forge
            - bioconda
            - defaults
        create-args: >-
          samtools
          htslib
          python=${{ env.PYTHON_VERSION }}
          annonars=${{ env.ANNONARS_VERSION }}

    - name: Cache annonars import output
      # Enable this if cache was not hit (we need to rebuild) or we publish and
      # then need the cache in any case.
      if: |
        (steps.check-cache-annonars-clinvar-genes-import-output.outputs.cache-hit != 'true') ||
        (inputs.publish-artifacts == 'true')
      uses: actions/cache@v3
      with:
        path: ${{ env.OUTPUT_DIR }}/${{ matrix.genome_release }}/seqvar/annonars-import
        key: annonars-clinvar-genes-import-${{ env.CACHE_SEED }}-${{ steps.get-clinvar.outputs.clinvar-release }}-${{ env.MAX_RCVS }}-${{ matrix.genome_release }}

    - name: Retrieve download-clinvar output
      if: steps.check-cache-annonars-clinvar-genes-import-output.outputs.cache-hit != 'true'
      uses: actions/cache@v3
      with:
        path: ${{ env.CLINVAR_JSONL_DIR }}
        key: download-clinvar-${{ env.CACHE_SEED }}-${{ steps.get-clinvar.outputs.clinvar-release }}
        fail-on-cache-miss: true

    - name: Run the annonars import
      if: steps.check-cache-annonars-clinvar-genes-import-output.outputs.cache-hit != 'true'
      run: bash .github/actions/clinvar-genes-import/run.sh
      env:
        GENOME_RELEASE: "${{ matrix.genome_release }}"
        CLINVAR_RELEASE: "${{ steps.get-clinvar.outputs.clinvar-release }}"
      # cf. https://github.com/mamba-org/provision-with-micromamba#important
      shell: bash -l {0}

    - name: Publish artifacts
      if: inputs.publish-artifacts == 'true'
      run: |
        set -xv

        version=$(\
            grep ^dc.identifier \
              $OUTPUT_DIR/clinvar-genes/spec.yaml \
            | rev \
            | cut -d - -f 1 \
            | rev)

        mkdir -p /tmp/for-upload/annonars-clinvar-genes-$version
        rsync -av \
          $OUTPUT_DIR/clinvar-genes/. \
          /tmp/for-upload/annonars-clinvar-genes-$version/.
        ls -lhR /tmp/for-upload/annonars-clinvar-genes-$version
        tar --directory=/tmp/for-upload --create --owner=0:0 --gzip \
          --file /tmp/for-upload/annonars-clinvar-genes-$version.tar.gz \
          annonars-clinvar-genes-$version

        pushd /tmp/for-upload
        sha256sum annonars-clinvar-genes-$version.tar.gz \
        > annonars-clinvar-genes-$version.tar.gz.sha256
        popd

        gh release upload --clobber "clinvar-weekly-${{ inputs.release-name }}" \
          /tmp/for-upload/annonars-clinvar-genes-$version.tar.gz*
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
      # cf. https://github.com/mamba-org/provision-with-micromamba#important
      shell: stdbuf -oL bash -l {0}
